server:
  port: 9000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/vacation?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValueSalonBankers # 다시 설정하기
  access-token:
    plus-hour: 6
  refresh-token:
    plus-hour: 12
